run-name: "${{ github.ref_name }} (${{ github.event_name }})"
on:
  issue_comment:
    types:
      - created
      - edited
permissions:
  pull-requests: write
  actions: write
  issues: write
  id-token: write
  contents: write
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: Loyverse/loyverse-actions/comment-event-handler@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dispatch-workflow-script-name-for-build: handler.yml